export default {
  covid19: [
    'covid-19',
    'covid 19',
    'covid19',
    'covid_19',
    'covid',
    '2019-ncov',
    '2019 ncov',
    '2019ncov',
    'ncov',
    'sars-cov-2',
    'sars cov 2',
    'sars cov2',
    'sarscov2',
    'corona-virus',
    'corona virus',
    'coronavirus',
  ],
  medicamentos: [
    'acetaminofen',
    'paracetamol',
    'tylenol',
    'dolex',
    'ibuprofeno',
    'metil-prednisolona',
    'metil prednisolona',
    'metilprednisolona',
    'prednisolona',
    'dexametasona',
    'cloroquina',
    'cloroquina',
    'hidroxi cloroquina',
    'hidroxicloroquina',
    'azitromicina',
    'ivermectina',
    'interferon',
    'remdesivir',
  ],
  organizaciones: [
    'Minsalud',
    'Ministerio de Salud',
    'Ministerio de Salud y Proteccion Social',
    'INS',
    'Instituto Nacional de Salud',
    'INVIMA',
    'Instituto Nacional de Vigilancia de Medicamentos y Alimentos',
    'SuperSalud',
    'Superintendencia Nacional de Salud',
    'DNP',
    'Departamento Nacional de Planeacion',
    'INC',
    'Instituto Nacional de Cancerologia',
    'Colciencias',
    'Asociacion Colombiana de Sociedades Cientificas',
    'Asociacion Colombiana de Clinicas y Hospitales',
    'ASCOFAME',
    'Asociacion Colombiana de Facultades de Medicina',
    'Asi Vamos En Salud',
    'Asi Es Salud',
    'WHO',
    'OMS',
    'Organizacion Mundial de la Salud',
    'OPS',
    'Organizacion Panamericana de la Salud',
    'OISS',
    'Organizacion Iberoamericana de Seguridad Social',
  ],
  procedimientosMedicos: [
    'consulta prioritaria',
    'consulta medica',
    'chequeo general',
    'hospitalizacion',
    'UCI',
    'cuidado intensivo',
    'servicio emergencia',
    'departamento emergencia',
    'PCR',
    'antigeno',
    'anticuerpo',
    'prueba',
    'test',
    'cuadro hematico',
    'hemograma',
    'temperatura',
    'saturacion oxigeno',
    'oximetro',
    'oximetria',
    'radiografia',
    'rayos-x',
    'rayos x',
    'rayosx',
  ],
  vacunacion: [
    'vacunacion',
    'vacuna',
    'pfizer',
    'moderna',
    'sinovac',
    'janssen',
    'johnson & johnson',
    'johnson johnson',
    'j&j',
    'dosis',
    'intervalo dosis',
    'tiempo dosis',
    'interdosis',
    'tiempo interdosis',
    'primera dosis',
    'segunda dosis',
    'tercera dosis',
    'dosis refuerzo',
  ],
  aspectosVirales: [
    'inmunidad',
    'incubacion',
    'difusion',
    'propagacion',
    'transmision',
    'contagio',
    'infeccion',
    'carga viral',
  ],
  medidasDeBioseguridad: [
    'mascara',
    'mascarilla',
    'tapabocas',
    'cuarentena',
    'aislamiento',
    'quedate casa',
    'distanciamiento',
    'lavado manos',
    'lavar manos',
    'desinfeccion',
  ],
  signosSintomas: [
    'ageusia',
    'gusto',
    'perdida del gusto',
    'saborear',
    'no saborear',
    'no poder saborear',
    'anosmia',
    'olfato',
    'perdida del olfato',
    'oler',
    'no oler',
    'no poder oler',
    'perdida del apetito',
    'apetito',
    'gripa',
    'gripe',
    'rinitis',
    'nariz tapada',
    'epistaxis',
    'sangrado por la nariz',
    'sangre por la nariz',
    'moco',
    'estornudo',
    'dolor de garganta',
    'odinofagia',
    'dificultad para respirar',
    'problemas para respirar',
    'respirar',
    'no respirar',
    'no poder respirar',
    'catarro',
    'tos',
    'tos seca',
    'conjuntivitis',
    'cara azul',
    'labios azules',
    'neumonia',
    'nausea',
    'dolor de estomago',
    'diarrea',
    'soltura',
    'vomito',
    'rash',
    'sarpullido',
    'brote',
    'taquicardia',
    'bradicardia',
    'frecuencia cardiaca',
    'latidos',
    'taquipnea',
    'bradipnea',
    'frecuencia respiratoria',
    'presion alta',
    'hipertension',
    'presion sanguinea alta',
    'dolor general',
    'dolores generalizados',
    'dolor muscular',
    'dolor en los musculos',
    'dolor en las articulaciones',
    'dolor articular',
    'dolor de pecho',
    'dolor en el pecho',
    'presion de pecho',
    'presion en el pecho',
    'alteracion de la conciencia',
    'perdida de la conciencia',
    'fatiga',
    'cansancio',
    'escalofrios',
    'mareo',
    'vertigo',
    'fiebre',
    'dolor de cabeza',
    'cefalea',
    'migraña',
  ],
  SSGusto: ['ageusia', 'gusto', 'sabor', 'saborear'],
  SSOlfato: ['anosmia', 'olfato', 'olor', 'oler'],
  SSConstitucionales: [
    'apetito',
    'taquicardia',
    'bradicardia',
    'frecuencia cardiaca',
    'latidos',
    'taquipnea',
    'bradipnea',
    'frecuencia respiratoria',
    'presion arterial',
    'tension arterial',
    'hipertension',
    'hipotension',
    'presion alta',
    'tension alta',
    'presion baja',
    'tension baja',
    'dolor general',
    'dolores generalizados',
    'dolor muscular',
    'dolor musculos',
    'dolor articular',
    'dolor articulaciones',
    'alteracion conciencia',
    'perdida conciencia',
    'fatiga',
    'cansancio',
    'escalofrios',
    'mareo',
    'vertigo',
    'malestar general',
    'dolor cabeza',
    'cefalea',
    'migraña',
  ],
  SSInfeccion: ['gripa', 'gripe', 'odinofagia', 'dolor garganta', 'conjuntivitis', 'fiebre'],
  SSRespiratorios: [
    'rinitis',
    'rinorrea',
    'nariz tapada',
    'congestion nasal',
    'epistaxis',
    'sangrado nariz',
    'sangre nariz',
    'moco',
    'estornudo',
    'respirar',
    'respiracion',
    'catarro',
    'tos',
    'cara azul',
    'labios azules',
    'dedos azules',
    'neumonia',
    'bronquitis',
    'bronconeumonia',
    'bronco neumonia',
    'bronco-neumonia',
    'dolor pecho',
    'presion pecho',
  ],
  SSGastrointestinales: [
    'nausea',
    'vomito',
    'dolor estomago',
    'diarrea',
    'soltura',
    'dolor abdominal',
    'dolor abdomen',
    'malestar estomacal',
  ],
  SSDermatologicos: ['rash', 'sarpullido', 'brote'],
};
